import { promises as fs } from "node:fs";
import os from "node:os";
import path from "node:path";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { supabase } from "./../storage/supabaseClient.js";
import { assetPaths, downloadAsset, uploadAsset, getSignedAssetUrl } from "../storage/assetStorage.js";
import { getProject, saveProject, advanceStage } from "./project.service.js";
import type { Block } from "../models/index.js";

const execFileAsync = promisify(execFile);

interface BlockRow {
  index: number;
  approval_status: Block["approvalStatus"];
  approved_clip_path: string | null;
}

export class AssembleValidationError extends Error {
  constructor(public readonly issues: string[]) {
    super(`Cannot assemble final video: ${issues.join("; ")}`);
    this.name = "AssembleValidationError";
  }
}

export async function assembleProject(projectId: string) {
  const project = await getProject(projectId);
  if (!project) throw new Error("Project not found");
  if (!project.voiceover) throw new Error("No voiceover uploaded");

  const { data: rows, error } = await supabase
    .from("blocks")
    .select("index, approval_status, approved_clip_path")
    .eq("project_id", projectId)
    .order("index");
  if (error) throw error;

  const blocks = rows as BlockRow[];
  const issues: string[] = [];
  if (blocks.length === 0) issues.push("No blocks planned yet");
  for (const b of blocks) {
    if (b.approval_status !== "approved" || !b.approved_clip_path) {
      issues.push(`Block ${b.index} is not approved yet`);
    }
  }
  if (issues.length > 0) throw new AssembleValidationError(issues);

  const tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), "assemble-"));
  try {
    // Download each approved clip and the voiceover into local temp files —
    // ffmpeg needs real files on disk, not in-memory buffers/streams.
    const clipPaths: string[] = [];
    for (const b of blocks) {
      const { buffer } = await downloadAsset(b.approved_clip_path as string);
      const clipPath = path.join(tmpDir, `block-${b.index}.mp4`);
      await fs.writeFile(clipPath, buffer);
      clipPaths.push(clipPath);
    }

    const { buffer: voiceoverBuffer } = await downloadAsset(project.voiceover.mp3Path);
    const voiceoverPath = path.join(tmpDir, "voiceover.mp3");
    await fs.writeFile(voiceoverPath, voiceoverBuffer);

    // Concatenate clips in block order (all generated by the same Veo model
    // with identical codec/resolution, so a stream-copy concat is safe).
    const concatListPath = path.join(tmpDir, "concat.txt");
    await fs.writeFile(concatListPath, clipPaths.map((p) => `file '${p.replace(/'/g, "'\\''")}'`).join("\n"));
    const concatenatedPath = path.join(tmpDir, "concatenated.mp4");
    await execFileAsync("ffmpeg", [
      "-y",
      "-f", "concat",
      "-safe", "0",
      "-i", concatListPath,
      "-c", "copy",
      concatenatedPath,
    ]);

    // Mux with the voiceover as the sole audio track (working assumption per
    // the plan — final-mix behavior, e.g. keeping some clip ambience under
    // the voiceover, is still an open decision to revisit later).
    const outputPath = path.join(tmpDir, "final.mp4");
    await execFileAsync("ffmpeg", [
      "-y",
      "-i", concatenatedPath,
      "-i", voiceoverPath,
      "-map", "0:v:0",
      "-map", "1:a:0",
      "-c:v", "copy",
      "-c:a", "aac",
      "-shortest",
      outputPath,
    ]);

    const finalBuffer = await fs.readFile(outputPath);
    const filename = `output-${project.dimension}-${Date.now()}.mp4`;
    const objectKey = assetPaths.final(projectId, filename);
    await uploadAsset(objectKey, finalBuffer, "video/mp4");

    project.finalOutputPath = objectKey;
    advanceStage(project, "ASSEMBLED");
    return saveProject(project);
  } finally {
    await fs.rm(tmpDir, { recursive: true, force: true });
  }
}

// Quick sanity-check merge of whatever clips have been generated so far —
// unlike assembleProject, this does NOT require every block to be approved
// and does NOT mux in the voiceover; it's just a fast "does the visual flow
// between these clips look right" preview while testing generation on a
// handful of scenes at a time.
export async function mergePreviewClips(projectId: string): Promise<{ url: string; mergedCount: number }> {
  const project = await getProject(projectId);
  if (!project) throw new Error("Project not found");

  const { data: rows, error } = await supabase
    .from("blocks")
    .select("index, approval_status, approved_clip_path, clip_attempts")
    .eq("project_id", projectId)
    .order("index");
  if (error) throw error;

  interface PreviewRow {
    index: number;
    approval_status: Block["approvalStatus"];
    approved_clip_path: string | null;
    clip_attempts: { path: string; status: string }[];
  }

  const clipPaths: string[] = [];
  for (const row of rows as PreviewRow[]) {
    if (row.approval_status !== "clip_review" && row.approval_status !== "approved") continue;
    const latestSucceeded = [...row.clip_attempts].reverse().find((a) => a.status === "succeeded");
    const path = row.approved_clip_path ?? latestSucceeded?.path;
    if (path) clipPaths.push(path);
  }

  if (clipPaths.length === 0) throw new Error("No generated clips to merge yet");

  const tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), "merge-preview-"));
  try {
    const localPaths: string[] = [];
    for (let i = 0; i < clipPaths.length; i++) {
      const { buffer } = await downloadAsset(clipPaths[i]);
      const localPath = path.join(tmpDir, `clip-${i}.mp4`);
      await fs.writeFile(localPath, buffer);
      localPaths.push(localPath);
    }

    const concatListPath = path.join(tmpDir, "concat.txt");
    await fs.writeFile(concatListPath, localPaths.map((p) => `file '${p.replace(/'/g, "'\\''")}'`).join("\n"));
    const outputPath = path.join(tmpDir, "preview.mp4");
    await execFileAsync("ffmpeg", ["-y", "-f", "concat", "-safe", "0", "-i", concatListPath, "-c", "copy", outputPath]);

    const buffer = await fs.readFile(outputPath);
    const objectKey = assetPaths.preview(projectId, `preview-${Date.now()}.mp4`);
    await uploadAsset(objectKey, buffer, "video/mp4");

    return { url: await getSignedAssetUrl(objectKey), mergedCount: clipPaths.length };
  } finally {
    await fs.rm(tmpDir, { recursive: true, force: true });
  }
}

export async function getFinalVideoUrl(projectId: string): Promise<string | null> {
  const project = await getProject(projectId);
  if (!project?.finalOutputPath) return null;
  return getSignedAssetUrl(project.finalOutputPath);
}
